class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror'
        self.UnzipMirrorCommand = 'unzipmirror'
        self.ZipMirrorCommand = 'zipmirror'
        self.ZipWatchCommand = 'zipwatch'
        self.QbMirrorCommand = 'qbmirror'
        self.QbUnzipMirrorCommand = 'qbunzipmirror'
        self.QbZipMirrorCommand = 'qbzipmirror'
        self.QbLeechCommand = 'qbleech'
        self.QbUnzipLeechCommand = 'qbunzipleech'
        self.QbZipLeechCommand = 'qbzipleech'
        self.UnzipLeechCommand = 'unzipleech'
        self.ZipLeechCommand = 'zipleech'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'list'
        self.SearchCommand = 'search'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'user'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone'
        self.CountCommand = 'count'
        self.WatchCommand = 'watch'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'usage'
        self.MediaInfoCommand = 'mediainfo'
        self.ShellCommand = 'shell'
        self.ExecHelpCommand = 'exechelp'
        self.LeechSetCommand = 'setleech'
        self.SetThumbCommand = 'setthumb'
        self.LeechCommand = 'leech'
        self.LeechWatchCommand = 'leechwatch'
        self.LeechZipWatchCommand = 'leechzipwatch'


BotCommands = _BotCommands()
